language: python
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

python:
- 3.6

os:
- linux

addons:
  apt:
    packages:
    - gfortran
    
matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script: 
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov
    - coveralls

install: pip install -e .[tests]

script:
- pytest -rsv


